## Code for running the constrained quadratic programming simulation study.

## In this simulation study, we generate $\mathbf{Q} as $\mathbf{Q} = \mathbf{U}\mathbf{D}\mathbf{U}^{T}$ 
## where $\mathbf{U} = (\mathbf{B}^{T}\mathbf{B})^{-1/2}$ and 
## B \in \mathbb{R}^{p \times p} was generated by drawing
## each element $B_{ij}$ from a Gaussian distribution with mean 0 and standard deviation 1. 
## To ensure the condition number of $\mathbf{Q}$ was equal to $\kappa$, we defined the matrix 
## $\mathbf{D}_{p}$ as $\mathbf{D}_{p} = \textrm{diag}\{ d_{1}, \ldots, d_{p} \}$
## where $\log d_{j} = \log(\kappa)\{1 - (j-1)/(p-1)\}$. 
## We generated the elements $q_{j}$ of the vector $\mathbf{q}$ as 
## $q_{j} = \frac{\varepsilon_{j}}{p-1}\frac{\sum_{i=1}^{p}(Q_{ij} - \bar{Q}_{.j})^{2}$,
## where $\varepsilon_{j}$ are Gaussian random variables with mean 0 and standard deviation 1/5.

setwd("~/Documents/nidaarem_reproduce")
source("SimulationCode/ConstrainedQuadraticProgram/ConstrainedQPFunctions.R")


library(nidaarem)
library(SQUAREM)

set.seed(314127)

## specify maximum number of iterations, covergence tolerance,
## condition number(for the steplength)
ni <- 500000
tols <- 1e-7
c.number <- 10^7

## specify dimension of Q matrix for simulations
## Q will be p x p
p <- 1000

#####################################################################
## Use 100 simulation replications
nreps <- 100

## Setup storage for number of iterations (NI), final objective function
## values (Obj), convergence information (Conv), and timing (Time):
NIDAARAMNI <- DAARAMNI <- SQNI <- RENESTNI <- NIDAAREMNI <- rep(NA, nreps)
NESTNI <- PGDNI <- MPENI <- rep(NA, nreps)
NIDAARAMObj <- DAARAMObj <- SQObj <- RENESTObj <- NIDAAREMObj <- rep(NA, nreps)
NESTObj <- PGDObj <- MPEObj <- rep(NA, nreps)
NIDAARAMConv <- DAARAMConv <- SQConv <- RENESTConv <- NIDAAREMConv <- rep(NA, nreps)
NESTConv <- PGDConv <- MPEConv <- rep(NA, nreps)
NIDAARAMTime <- DAARAMTime <- SQTime <- RENESTTime <- NIDAAREMTime <- rep(NA, nreps)
NESTTime <- PGDTime <- MPETime <- rep(NA, nreps)

for(j in 1:nreps) {
  tmp <- SimulateConstrQP(n=p, cond.number=c.number)
  x.init <- rnorm(p)
  stp <- 1/c.number
  
  ans.pgd.time <- system.time(ans.pgd <- fpiter(par=x.init, fixptfn=ConstrQPFixpt, objfn=ConstrQPObj, Q=tmp$Q, q=tmp$q, a=-1, b=1, stplength=stp, 
                                                control=list(maxiter=ni, tol=tols)))
  
  ans.nest.time <- system.time(ans.nest <- Nesterov(par=x.init, fixptfn=ConstrQPFixpt, objfn=ConstrQPObj, Q=tmp$Q, q=tmp$q, a=-1, b=1, stplength=stp,
                                                    restart=FALSE, control=list(maxiter=ni, tol=tols)))
  
  ans.renest.time <- system.time(ans.renest <- Nesterov(par=x.init, fixptfn=ConstrQPFixpt, objfn=ConstrQPObj, Q=tmp$Q, q=tmp$q, a=-1, b=1, stplength=stp,
                                                        restart=TRUE, control=list(maxiter=ni, tol=tols)))
  
  ans.daaram.time <- system.time(ans.daaram <- nidaarem(par=x.init, fixptfn=ConstrQPFixpt, objfn=ConstrQPObj, nesterov.init=FALSE, 
                                                        Q=tmp$Q, q=tmp$q, a=-1, b=1, stplength=stp, control=list(maxiter=ni, order=5, 
                                                                                                                 mon.tol=c(1,0), tol=tols)))
 
  ans.nidaaram.time <- system.time(ans.nidaaram <- nidaarem(par=x.init, fixptfn=ConstrQPFixpt, objfn=ConstrQPObj, nesterov.init=TRUE, 
                                                            Q=tmp$Q, q=tmp$q, a=-1, b=1, stplength=stp, control=list(maxiter=ni, order=5, 
                                                                                                                     mon.tol=c(1,0), tol=tols)))
  
  ans.nidaarem.time <- system.time(ans.nidaarem <- nidaarem(par=x.init, fixptfn=ConstrQPFixpt, objfn=ConstrQPObj, nesterov.init=TRUE, 
                                                            Q=tmp$Q, q=tmp$q, a=-1, b=1, stplength=stp, control=list(maxiter=ni, order=5, 
                                                                                                                     mon.tol=1, tol=tols)))
  
  ans.sq.time <- system.time(ans.sq <- squarem(par=x.init, fixptfn=ConstrQPFixpt, objfn=ConstrQPNegObj, Q=tmp$Q, q=tmp$q, a=-1, b=1, stplength=stp, 
                                               control=list(maxiter=ni, tol=tols)))
  
  ans.mpe.time <- system.time(ans.mpe <- squarem(par=x.init, fixptfn=ConstrQPFixpt, objfn=ConstrQPNegObj, Q=tmp$Q, q=tmp$q, a=-1, b=1, stplength=stp,
                                                 control=list(maxiter=ni, tol=tols, K=3, method="MPE")))
  
  #ans.snidaarem.time <- system.time(ans.snidaarem <- sdaarem.lasso(par=beta.init, X=XX, y=yy, lambda=lam, stplngth=stp, nesterov.init=TRUE, 
  #                                                                 sub.type="threshold", control=list(tol=tols, order=5, maxiter=ni, mon.tol=c(1,0))))
  
  #ans.sdaarem.time <- system.time(ans.sdaarem <- sdaarem.lasso(par=beta.init, X=XX, y=yy, lambda=lam, stplngth=stp, nesterov.init=FALSE, 
  #                                                             sub.type="threshold", control=list(tol=tols, order=5, maxiter=ni, mon.tol=c(1,0))))
  
  DAARAMNI[j] <- ans.daaram$fpevals
  NIDAARAMNI[j] <- ans.nidaaram$fpevals
  SQNI[j] <- ans.sq$fpevals
  RENESTNI[j] <- ans.renest$fpevals
  NESTNI[j] <- ans.nest$fpevals
  PGDNI[j] <- ans.pgd$fpevals
  MPENI[j] <- ans.mpe$fpevals
  NIDAAREMNI[j] <- ans.nidaarem$fpevals
  
  DAARAMObj[j] <- ans.daaram$value.objfn
  NIDAARAMObj[j] <- ans.nidaaram$value.objfn
  SQObj[j] <- (-1)*ans.sq$value.objfn
  RENESTObj[j] <- ans.renest$value.objfn
  NESTObj[j] <- ans.nest$value.objfn
  PGDObj[j] <- ans.pgd$value.objfn
  MPEObj[j] <- (-1)*ans.mpe$value.objfn
  NIDAAREMObj[j] <- ans.nidaarem$value.objfn
  
  DAARAMConv[j] <- ans.daaram$convergence
  NIDAARAMConv[j] <- ans.nidaaram$convergence
  SQConv[j] <- ans.sq$convergence
  RENESTConv[j] <- ans.renest$convergence
  NESTConv[j] <- ans.nest$convergence
  PGDConv[j] <- ans.pgd$convergence
  MPEConv[j] <- ans.mpe$convergence
  NIDAAREMConv[j] <- ans.nidaarem$convergence
  
  DAARAMTime[j] <- ans.daaram.time[3]
  NIDAARAMTime[j] <- ans.nidaaram.time[3]
  SQTime[j] <- ans.sq.time[3]
  RENESTTime[j] <- ans.renest.time[3]
  NESTTime[j] <- ans.nest.time[3]
  PGDTime[j] <- ans.pgd.time[3]
  MPETime[j] <- ans.mpe.time[3]
  NIDAAREMTime[j] <- ans.nidaarem.time[3]
  
  print(j)
}

#save(NIDAARAMNI, DAARAMNI, SQNI, RENESTNI, NESTNI, PGDNI, MPENI, NIDAAREMNI, 
#     NIDAARAMObj, DAARAMObj, SQObj, RENESTObj, NESTObj, PGDObj, MPEObj, NIDAAREMObj,
#     NIDAARAMConv, DAARAMConv, SQConv, RENESTConv, NESTConv, PGDConv, MPEConv, NIDAAREMConv, 
#     NIDAARAMTime, DAARAMTime, SQTime, RENESTTime, NESTTime, PGDTime, MPETime, NIDAAREMTime,
#     file="SimulationResults/ConstrainedQuadraticProgram/ConstrainedQPSimResults.RData")

